<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="7JP2SJ2" name="Test" tests="3" failures="1" timestamp="26 Jul 2018 06:33:17 GMT" time="0.062" errors="0">
  <testcase name="test1" time="0.031" classname="com.experitest.auto.test"/>
  <testcase name="test2" time="0.0" classname="com.experitest.auto.test"/>
  <testcase name="test3" time="0.016" classname="com.experitest.auto.test">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at com.experitest.auto.test.test3(test.java:23)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test -->
